export const GEMINI_REQUEST_TIMEOUT_MS = 30_000;
export const OLLAMA_HEALTH_TIMEOUT_MS = 1_000;

export const AI_TUTOR_RATE_LIMIT_DEFAULT_MAX = 5;
export const AI_TUTOR_RATE_LIMIT_DEFAULT_WINDOW_SECONDS = 60;
export const AI_TUTOR_DAILY_QUOTA_DEFAULT = 100;
export const AI_TUTOR_CONCURRENCY_LOCK_DEFAULT_TTL_SECONDS = 120;

export const AI_TUTOR_PROVIDER_TIMEOUT_BUFFER_SECONDS = 5;
