import type { Course } from "@/lib/courses/types";
import {
  NDF_PACKET_VIEW_VIDEO_PATH,
  NDF_SERVICE_REVIEW_VIDEO_PATH,
  NDF_TRAFFIC_MAP_VIDEO_PATH,
} from "@/lib/courses/local-lesson-video-overrides";

export const mockCourses: Course[] = [
  {
    id: "network-defense-foundations",
    title: "Network Defense Foundations",
    category: "Blue Team",
    shortDescription:
      "Build the baseline skills for reading traffic, spotting weak signals, and hardening a small network.",
    fullDescription:
      "A practical introduction to defensive networking for new operators. You will learn how traffic moves, where useful evidence appears, and how to turn basic observations into a repeatable investigation workflow.",
    difficulty: "beginner",
    tone: "cyan",
    hasLabs: true,
    sections: [
      {
        id: "ndf-orientation",
        title: "Orientation",
        description: "Core concepts for thinking clearly about network defense.",
        order: 1,
        lessons: [
          {
            id: "ndf-traffic-map",
            title: "Reading the Traffic Map",
            type: "HYBRID",
            contentMode: "HYBRID",
            durationMinutes: 12,
            order: 1,
            summary: "Understand hosts, services, ports, and the path an event takes through a network.",
            video: {
              src: NDF_TRAFFIC_MAP_VIDEO_PATH,
              contentType: "video/mp4",
              title: "Reading the Traffic Map",
            },
            media: {
              video: {
                src: NDF_TRAFFIC_MAP_VIDEO_PATH,
                contentType: "video/mp4",
                title: "Reading the Traffic Map",
              },
            },
            articleContent: [
              "Network defense starts with a map of normal movement. Identify the hosts involved, the service being requested, the port in use, and the direction of the connection before deciding whether an event is suspicious.",
              "A useful first pass separates expected business traffic from traffic that needs review. Look for unfamiliar destinations, unexpected listening services, repeated failures, and protocol choices that do not fit the asset.",
              "For the MVP, treat this lesson as a structured reading module. Later, the lab backend can attach packet captures and scoring events to the same lesson record.",
            ],
          },
          {
            id: "ndf-packet-view",
            title: "Packet Capture Walkthrough",
            type: "HYBRID",
            contentMode: "HYBRID",
            durationMinutes: 9,
            order: 2,
            summary:
              "Learn how defenders use packet captures to map network conversations and investigate anomalies.",
            video: {
              src: NDF_PACKET_VIEW_VIDEO_PATH,
              contentType: "video/mp4",
              title: "Packet Capture Walkthrough",
            },
            media: {
              video: {
                src: NDF_PACKET_VIEW_VIDEO_PATH,
                contentType: "video/mp4",
                title: "Packet Capture Walkthrough",
              },
            },
            articleContent: [
              "Packet Capture Walkthrough: Mastering Network Visibility for Defense",
              "Lesson Summary",
              "In the modern cybersecurity landscape, defenders must move beyond simple alerts to understand the \"ground truth\" of what is happening on their networks. Packet captures, or PCAPs, are the digital records of every communication that crosses a network interface, providing a granular level of detail that logs alone often miss. This lesson is a foundational guide for beginner defenders, teaching them how to collect, read, and analyze these digital footprints to build visibility and respond to events with precision.",
              "By mastering the art of the packet walkthrough, students will learn to transition from viewing a network as a black box to seeing it as a series of structured, identifiable conversations. We will explore the building blocks of network traffic, from the initial handshake to complex application-layer exchanges, and apply these concepts in a realistic defensive environment. This skill is a prerequisite for achieving digital resilience and maintaining an always-on security posture.",
              "Finally, we will examine the professional methodologies used by security operation centers, or SOCs, to map communications. You will learn how to distinguish between expected business traffic and unusual behavior, using tools like Wireshark to visualize data flows and protect critical assets. This lesson is not just about tools; it is about developing the defensive mindset required to protect an organization's most sensitive data.",
              "Why This Matters",
              "Packet captures are the gold standard of evidence for network defenders and incident responders. While high-level logs tell you that a connection happened, a packet capture shows you exactly how it happened and what data was exchanged.",
              "This visibility helps defenders verify security controls. A defender can use a PCAP to confirm whether a firewall successfully blocked unauthorized traffic or whether a rule needs adjustment.",
              "Packet analysis supports root cause analysis. When a critical application fails or behaves strangely, packet analysis allows defenders to see whether the issue is a network misconfiguration, a protocol error, or a potential security event.",
              "Packets help establish truth. Unlike logs, which can sometimes be modified or limited by what the system designer chose to record, packets are the raw data of the network. They provide an undeniable timeline of events.",
              "Packet metadata also creates visibility in encrypted environments. Even when traffic is encrypted, such as HTTPS, modern defensive analysis of packet metadata can reveal patterns and destinations that help defenders identify threats without decrypting sensitive content.",
              "Learning Objectives",
              "By the end of this lesson, students will be able to define a packet and explain the structure and purpose of a PCAP file in a defensive context.",
              "Students will be able to identify and map source and destination IP addresses and ports to understand system relationships.",
              "Students will be able to analyze the protocol hierarchy to determine which types of traffic are most prevalent on a network.",
              "Students will be able to navigate network conversations to follow a complete session between a client and a server.",
              "Students will be able to apply a structured defender workflow to investigate anomalies and document findings for a security team.",
              "Prerequisites",
              "Before studying this lesson, students should be familiar with networking basics, including a foundational understanding of how devices connect to the internet.",
              "Students should understand the client-server model, including how a client such as a web browser requests data from a server such as a website.",
              "Students should recognize the format of basic IPv4 addresses.",
              "Introduction",
              "Imagine you are a digital detective. A call comes in: an internal server at a hospital is acting sluggish, and the security team notices it is sending data to an unknown location on the internet. You have the logs, but they only show a list of timestamps and IP addresses. To truly solve the mystery, you need to see the DNA of the communication. You need to see the packets.",
              "Packet captures are the black box flight recorders of the digital world. Every time your computer loads a webpage, sends an email, or connects to a database, it breaks that information into small pieces called packets. As a defender, learning to read these packets is like learning to read the fingerprints left behind at a scene. In this lesson, we will walk through the process of capturing these fingerprints and using them to build a map of network activity, ensuring that your organization remains secure and resilient.",
              "Core Concepts",
              "A packet is the basic unit of data transmitted over a network. Think of it like a physical envelope. Inside is the payload, which is the actual data, and on the outside is the header, which contains the addressing information. As data moves through the network, it undergoes encapsulation, where different layers add their own headers like a box inside another box.",
              "A packet capture, often stored in a .pcap or .pcapng file, is a recording of live network traffic. Defenders use specialized software to sniff the traffic passing through a network interface and save it for later analysis.",
              "Every packet contains the source IP, which identifies who sent it, and the destination IP, which identifies who is supposed to receive it. Mapping these addresses allows defenders to identify which specific hosts are communicating on the network.",
              "Ports are like doors on a building. While an IP address gets you to the building, the port tells you which room or service to go to. The destination port is usually a well-known port like 80 for HTTP or 443 for HTTPS that identifies the service being requested. The source port is a random, high-numbered port assigned by the client's operating system to keep track of that specific conversation.",
              "Protocols are the languages computers use to speak. TCP is a reliable, connection-oriented protocol that ensures every packet arrives in the correct order using a three-way handshake. UDP is a faster, best-effort protocol often used for streaming or DNS.",
              "DNS traffic matters because the Domain Name System is the internet's phonebook. It translates human-friendly names, such as vincerecryptex.com, into IP addresses. Defenders watch DNS traffic to see what external sites internal users are trying to reach.",
              "HTTP is the protocol used for unencrypted web browsing. In a packet capture, HTTP traffic is plain text, meaning a defender can see the exact requests being made and the data being returned.",
              "HTTPS is HTTP secured by TLS, or Transport Layer Security. Most modern web traffic is encrypted. While a defender cannot see the payload without a decryption key, they can still see handshake metadata, which includes the destination website's name and the security certificates used.",
              "Every packet in a capture is marked with a timestamp. This is critical for defenders to reconstruct the exact sequence of events. Knowing whether a DNS request happened before or after a connection to a database can change the entire meaning of an investigation.",
              "A conversation, or session, is the complete exchange between two endpoints. Instead of looking at one isolated packet, defenders use Follow Stream features in tools like Wireshark to see the entire dialogue from start to finish.",
              "Traffic direction describes where communication is moving. Inbound traffic comes from the internet into the network. Outbound traffic leaves the internal network for the internet. Lateral or internal traffic moves between devices inside the same network.",
              "Defenders use segmentation to separate the internal world, where employees work, from the external world of the internet. A DMZ, or demilitarized zone, often sits in between, hosting public-facing services like web servers.",
              "Defensive Scenario: The Mismatched Middleware",
              "The setting: You are a junior defender at Contoso, a mid-sized company with a standard three-layer network architecture: frontend web servers, middleware application servers, and backend databases.",
              "The discovery: Your monitoring system triggers an alert. An application server in the middleware zone, which should only talk to the web server and the database, is attempting to communicate with an unknown IP address on the public internet.",
              "The investigation: You perform a packet capture on the middleware server's interface. You filter for the unknown IP address. You see a DNS request for a domain that looks like a legitimate software update site. You follow the TCP stream and see that the server is successfully connecting to port 443 over HTTPS. By looking at the TLS handshake, you confirm the certificate belongs to a trusted software vendor.",
              "The conclusion: The traffic is an authorized, automatic update that was not previously documented in the network baseline. You document the finding and update the firewall policy to allow this specific communication while remaining alert for other changes.",
              "Defender Workflow",
              "Professional defenders follow a systematic approach to analyze packet data.",
              "Collect packet capture data. Use a tool like Wireshark or tcpdump to capture traffic on a specific interface or from a network tap.",
              "Identify communicating systems. Open the Endpoints window to see a list of every IP address involved in the capture. This helps you identify the top talkers.",
              "Review protocols in use. Use the Protocol Hierarchy window to see what languages are being spoken. If you see File Transfer Protocol, or FTP, on a network that only uses web traffic, that is an immediate red flag.",
              "Analyze traffic conversations. Use the Conversations window to group packets into logical sessions. This allows you to see the story of how two devices interacted.",
              "Establish expected behavior. Compare your findings against the organization's written policy or baseline. Does the allowed traffic in the packets match what the network diagram says should happen?",
              "Investigate unusual activity. Use display filters to hide noise, such as standard background Windows traffic, and focus on specific ports or IP addresses that seem out of place.",
              "Document findings. Create a report including timestamps, endpoints, and protocol details. Use expert information from your tools to highlight any technical errors or unusual flags identified during the analysis.",
              "Common Mistakes",
              "Focusing on a single packet is a common beginner mistake. A single packet is rarely enough to understand a situation; you must look at the conversation or stream to see the full context.",
              "Ignoring timestamps can mislead an investigation. Network events often happen in milliseconds. If you do not pay attention to timestamps, you might mistake a response for a request or fail to see how multiple hosts are working together.",
              "Misinterpreting encrypted traffic is another common mistake. Many students assume that if they cannot see the payload of an HTTPS packet, the data is useless. However, metadata such as destination and certificate information is still extremely valuable for defense.",
              "Jumping to conclusions without context can create false alarms. An unusual port does not always mean there is a threat. It could be a misconfigured service or a new, undocumented business tool. Always verify with the system owners.",
              "Key Terms",
              "A packet is the smallest unit of data sent over a network.",
              "A frame is a packet as it exists at the local hardware, or Ethernet, layer.",
              "A protocol is a set of rules for communication, such as TCP, UDP, or HTTP.",
              "DNS, or Domain Name System, is the service that translates domain names to IP addresses.",
              "TCP, or Transmission Control Protocol, is a reliable, connection-oriented protocol using a three-way handshake.",
              "UDP, or User Datagram Protocol, is a lightweight, connectionless protocol used for speed.",
              "A session or conversation is a complete exchange of data between two endpoints.",
              "The payload is the actual data or content being carried inside a packet.",
              "TLS, or Transport Layer Security, is the protocol used to encrypt web traffic over HTTPS.",
              "PCAP is the standard file format for storing packet capture data.",
              "Practical Takeaways",
              "Visibility is the foundation. You cannot defend a network you cannot see. Packet captures provide the highest level of visibility available to a defender.",
              "Think in conversations. Do not get lost in individual packets. Always group traffic into sessions to understand the who, what, and why of a connection.",
              "Timestamps are your timeline. Use timestamps to build a chronological sequence of events. This is the only way to prove what happened first in a complex event.",
              "The baseline is your guide. You must know what normal looks like on your network before you can identify what is unusual.",
              "Metadata matters. Even in an encrypted world, packet headers and handshake information provide vital clues for defensive analysis.",
              "Lesson Wrap-Up",
              "Mastering the packet capture walkthrough is a transformative step in your journey as a network defender. By moving from high-level logs to granular packet analysis, you gain the ability to verify security controls, investigate anomalies, and maintain the digital resilience of your organization.",
              "Packet analysis is a skill that improves with practice. Start by capturing and analyzing your own normal traffic to become familiar with common protocols like DNS, HTTP, and TLS. As you become more comfortable navigating conversations and understanding traffic direction, you will become a more effective and decisive member of any cybersecurity team. Keep your focus on visibility, follow the defender workflow, and always let the packets tell the story.",
            ],
          },
        ],
      },
      {
        id: "ndf-hardening",
        title: "Hardening Basics",
        description: "Small configuration choices that reduce exposure fast.",
        order: 2,
        lessons: [
          {
            id: "ndf-service-review",
            title: "Service Exposure Review",
            type: "HYBRID",
            contentMode: "HYBRID",
            durationMinutes: 18,
            order: 1,
            summary: "Identify open services and decide which ones belong in the current environment.",
            video: {
              src: NDF_SERVICE_REVIEW_VIDEO_PATH,
              contentType: "video/mp4",
              title: "Service Exposure Review",
            },
            media: {
              video: {
                src: NDF_SERVICE_REVIEW_VIDEO_PATH,
                contentType: "video/mp4",
                title: "Service Exposure Review",
              },
            },
            articleContent: [
              "Service Exposure Review: Managing the Gateway to Your Network",
              "Lesson Summary",
              "In the complex landscape of modern networking, a defender's primary goal is to maintain a state of digital resilience. Achieving this requires a clear understanding of what services are running on the network and which of those services are accessible to others. This process, known as Service Exposure Review, is the systematic identification, documentation, and management of every listening application within an organization. By moving from a flat network where everything is exposed to a structured environment where exposure is strictly controlled, defenders can significantly reduce the risk of unauthorized access.",
              "This lesson guides students through the transition from identifying raw network data to making informed defensive decisions. Students will learn how to use professional methodologies, such as host discovery and port scanning basics, not for offensive purposes, but to build a comprehensive service inventory. We will explore how to apply the Principle of Least Privilege to network communications, ensuring that only the minimum necessary services are exposed to the minimum necessary audiences.",
              "Through practical examples and a realistic defensive scenario, students will learn how to prioritize risks based on network zones and trust boundaries. By the end of this lesson, you will understand how to document a network's ground truth and provide actionable recommendations to secure an organization's most critical assets, moving toward an always-on resilient posture.",
              "Why This Matters",
              "Service exposure review is a fundamental pillar of any robust defense strategy. It is not enough to simply have a firewall; a defender must know exactly what that firewall is allowing and why. This practice matters for several critical reasons.",
              "Attack Surface Reduction: The attack surface is the set of all active or interesting hosts and their listening services. By identifying and closing unnecessary services, a defender reduces the number of doors available for potential issues to enter the network.",
              "Visibility: You cannot defend what you cannot see. Gaining visibility into exposed services allows defenders to verify that security controls are functioning as intended.",
              "Risk Management: Aligning with frameworks like the NIST Cybersecurity Framework helps organizations understand and improve their management of cybersecurity risk. Reviewing exposure is a direct way to identify and mitigate high-risk configurations.",
              "Least Privilege: At the network level, least privilege means that a host should only be able to communicate with the specific services it requires for business operations.",
              "Exposure Control: Strategic exposure control ensures that sensitive systems, like databases, are never directly accessible from untrusted zones like the public internet.",
              "Learning Objectives",
              "By the end of this lesson, students will be able to define a network service and explain the defensive significance of service exposure.",
              "Students will be able to differentiate between public and internal services and map them to a three-layer network architecture.",
              "Students will be able to utilize host discovery techniques to identify active hosts and build a preliminary service inventory.",
              "Students will be able to apply business justification and service ownership criteria to prioritize risks during a review.",
              "Students will be able to document network communications using schematic symbols and define a paper network security policy.",
              "Prerequisites",
              "To succeed in this lesson, students should have an understanding of networking basics, including IP addresses and the client-server model.",
              "Students should be familiar with the difference between TCP and UDP protocols.",
              "Students should know common well-known ports, such as 80 for HTTP and 443 for HTTPS.",
              "Students should have a general awareness of what a firewall does: filtering traffic based on rules.",
              "Introduction",
              "In business, exposure is usually a good thing. You want your customers to find your website and use your services. However, in cybersecurity, exposure is a double-edged sword. Every service your company runs to make money or manage operations is a potential path into your network. If a web server needs to talk to a database to show a customer their account balance, that is a necessary business operation. If a guest in your lobby can also talk directly to that same database, that is a security risk.",
              "As a network defender, your job is to be the gatekeeper. You must understand the Traffic Map of your organization so well that you can spot an unnecessary door, or open port, from a mile away. In this lesson, we will learn how to perform a Service Exposure Review. We will go beyond just seeing what is open and start asking why it is open, who owns it, and should it be there. This is how professional defenders transform a chaotic network into a secured, resilient environment.",
              "Core Concepts",
              "What is a Network Service?",
              "A network service is an application or program running on a host that listens for incoming requests from other devices over a network. For example, a web server provides a web service by listening for requests from browsers.",
              "Service Exposure",
              "Exposure refers to the accessibility of a service. A service is exposed if it is reachable across a network boundary or from another security zone. Defenders aim to manage exposure so that services are only reachable by authorized users or systems.",
              "Public vs. Internal Services",
              "Public services are intended to be accessed from the public internet, such as the company's main website in the DMZ.",
              "Internal services should only be accessible within the company's private network, such as an internal payroll application or a file server.",
              "Open Ports and Listening Services",
              "Computers use ports to distinguish between different services. An open port is a state where a service is actively listening for a connection. Defenders use probes, such as TCP SYN packets, to identify these listening services.",
              "Attack Surface",
              "The attack surface is the sum total of all your exposed IP addresses, ports, and services. A primary goal of defense is to keep this surface as small as possible while still allowing the business to function.",
              "Business Justification and Service Ownership",
              "Every exposed service must have a business justification, a reason why it exists, such as allowing employees to log their hours. Furthermore, every service must have a service owner, a person or department responsible for its maintenance and security.",
              "Service Inventory",
              "A service inventory is a master list of all authorized services, their host IP addresses, the ports they use, and their business purpose. This is the defender's source of truth.",
              "Expected vs. Unexpected Services",
              "Expected services are documented in the inventory and required for business, such as a database responding to an application server.",
              "Unexpected services appear during a scan but have no documentation or clear purpose. These require immediate investigation.",
              "Network Zones and Trust Boundaries",
              "Defenders divide networks into security zones, such as Frontend, Middleware, and Backend. A trust boundary is a point, often a firewall, where traffic moves from a less-trusted zone to a more-trusted zone.",
              "Principle of Least Privilege",
              "This principle dictates that network access should be restricted to the minimum necessary for a service to operate. For example, a web server in the Frontend zone should be allowed to talk to an application server in the Middleware zone, but it should be prohibited from talking directly to a database in the Backend zone.",
              "Service Documentation",
              "Defenders use schematic symbols and diagrams to create a paper policy. This documentation describes the allowed rules and provides a clear guide for administrators and auditors.",
              "Defensive Scenario: The Mysterious Database Connection",
              "The setup: You are a defender for Contoso, an organization using a three-layer network architecture. Your network is divided into a Frontend zone for public web servers in the DMZ, a Middleware zone for application servers handling logic, and a Backend zone for databases and Active Directory services.",
              "The discovery: During a routine host discovery scan, you identify a host in the Backend zone, IP address 10.1.5.20, that is listening on port 3306 for MySQL database traffic.",
              "The review: You check the service inventory. 10.1.5.20 is listed as the Primary Customer Database. Port 3306 is an expected service.",
              "Exposure analysis: You check the firewall rules. You find that port 3306 is open not only to the Middleware servers, which is expected, but also to the Frontend web servers, which is unexpected.",
              "Decision making: According to the Contoso security policy, access from the Frontend directly to the Backend is prohibited. This bypasses the application logic and creates unnecessary risk.",
              "The action: You identify the Service Owner, the Database Team. They explain that the rule was created two weeks ago for a temporary troubleshooting task. You recommend a corrective action: immediately update the firewall to block Frontend-to-Backend traffic on port 3306, restoring the trust boundary.",
              "Defender Workflow",
              "A defender follows these nine steps to manage service exposure effectively.",
              "Identify exposed services. Use list scans or ping sweeps to find active hosts, followed by service discovery probes, such as TCP or UDP probes, to identify listening ports.",
              "Build a service inventory. Catalog the results, noting the IP address, port, protocol, and the service name, such as 192.168.1.5, Port 443, TCP, HTTPS.",
              "Determine ownership. Identify who in the organization is responsible for the host and the application running the service.",
              "Verify business purpose. Ask the owner why the service is exposed. Does it fulfill a requirement for customers, employees, or automated systems like Zabbix monitoring?",
              "Review exposure level. Determine where the service is visible. Is it exposed to the whole internet, the whole office, or only one specific server?",
              "Evaluate risk. Compare the exposure to the three-layer model. Does the communication path cross a trust boundary inappropriately, such as Middleware talking to an external CnC server?",
              "Document findings. Record everything in the service inventory and update the network security policy diagrams.",
              "Recommend corrective actions. If a service is unnecessary or overly exposed, recommend closing the port, moving the host to a different zone, or narrowing the firewall rules.",
              "Schedule future reviews. Service exposure is not a one-time task. Schedule regular, automated scans to ensure no new unexpected services have appeared.",
              "Common Mistakes",
              "Assuming every open service is malicious: Beginners often panic when they see an unknown port. Most unexpected services are actually undocumented business tools or misconfigured but legitimate applications.",
              "Ignoring undocumented services: Just because a service is not malicious does not mean it should be ignored. Every undocumented service is a gap in your visibility and a risk to the organization.",
              "Removing services without verifying business impact: Shutting down an exposed service without checking with the owner can crash critical business applications. Always verify business justification first.",
              "Failing to document ownership: A service without an owner is an orphaned service. When a security issue arises, if you do not know who owns it, you will not know how to fix it without causing a disruption.",
              "Leaving temporary exceptions permanently enabled: As seen in our scenario, temporary troubleshooting rules often become permanent security holes. Always set an expiration date for firewall exceptions.",
              "Key Terms",
              "Service: An application listening for network requests, such as a web server.",
              "Port: A numerical identifier from 0 to 65535 used to direct traffic to a specific service.",
              "Exposure: The state of being reachable across a network or from another security zone.",
              "Attack Surface: The set of all IP addresses and ports that are active and responsive.",
              "Service Inventory: A documented list of authorized hosts and services.",
              "Trust Boundary: A security perimeter, usually a firewall, separating different zones.",
              "Least Privilege: The practice of limiting access to only what is strictly necessary.",
              "Network Zone: A segment of the network grouped by function and security level, such as DMZ or Backend.",
              "Exception: A temporary or specific rule that deviates from the standard security policy.",
              "Service Owner: The person or team responsible for a specific network service.",
              "Practical Takeaways",
              "Map before you act. You must have an accurate map of your services, the inventory, before you can successfully defend them.",
              "The three-layer model is your blueprint. Use the Frontend, Middleware, and Backend zones to decide where a service belongs and who should talk to it.",
              "Every rule needs a why. Never allow a service to be exposed unless there is a documented business justification and a clear service owner.",
              "Visibility is continuous. Use automated tools to perform regular host discovery. The network changes every day; your map must keep up.",
              "Documentation is a defensive weapon. A clear paper policy makes it easier for everyone, from developers to auditors, to understand what is allowed and why.",
              "Lesson Wrap-Up",
              "Service Exposure Review is the process of bringing order to the potential chaos of a corporate network. By identifying active hosts, cataloging their services, and strictly managing their exposure according to the Principle of Least Privilege, you move your organization toward a state of digital resilience.",
              "Remember that your goal as a defender is not to hinder the business, but to ensure it can operate safely. By working through the defender workflow, identifying, verifying, and documenting, you provide the visibility necessary to protect critical assets and maintain an always-on resilient posture. As you continue your journey in network defense, always let the inventory be your guide and the security policy be your shield.",
            ],
          },
          {
            id: "ndf-firewall-rules",
            title: "Firewall Rule Hygiene",
            type: "TEXT",
            durationMinutes: 16,
            order: 2,
            summary: "Translate intended access into simple, auditable firewall rules.",
            articleContent: [
              "Good firewall rules are boring: specific source, specific destination, specific service, and a clear reason. Broad allow rules age badly and make incident review harder.",
              "When reviewing a rule set, group related rules by purpose, remove expired exceptions, and confirm that deny behavior is explicit enough for future operators to understand.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "web-application-attack-lab",
    title: "Web Application Attack Lab",
    category: "Application Security",
    shortDescription:
      "Practice safe exploitation patterns against intentionally vulnerable web surfaces.",
    fullDescription:
      "A guided course for understanding common web application flaws from the attacker perspective. The emphasis stays on controlled labs, evidence, and the mental model needed to report risks responsibly.",
    difficulty: "intermediate",
    tone: "purple",
    hasLabs: true,
    sections: [
      {
        id: "waa-recon",
        title: "Reconnaissance",
        description: "Map the app before touching exploit paths.",
        order: 1,
        lessons: [
          {
            id: "waa-surface-map",
            title: "Application Surface Mapping",
            type: "TEXT",
            durationMinutes: 15,
            order: 1,
            summary: "Catalog routes, inputs, auth boundaries, and data-bearing features.",
            articleContent: [
              "Surface mapping keeps testing disciplined. List routes, forms, API calls, role boundaries, and places where user-provided values are rendered or stored.",
              "A clear map prevents random probing. It also helps you explain why a finding matters when the same flaw appears across several similar endpoints.",
            ],
          },
          {
            id: "waa-proxy-tour",
            title: "Proxy Setup",
            type: "VIDEO",
            durationMinutes: 10,
            order: 2,
            summary: "Configure an intercepting proxy for controlled request inspection.",
            articleContent: [
              "The video placeholder represents a protected walkthrough. The final lesson can reuse this content slot when the media service is connected.",
            ],
          },
        ],
      },
      {
        id: "waa-exploitation",
        title: "Controlled Exploitation",
        description: "Validate impact without overreaching.",
        order: 2,
        lessons: [
          {
            id: "waa-injection",
            title: "Input Injection Signals",
            type: "HYBRID",
            durationMinutes: 22,
            order: 1,
            summary: "Use safe probes to identify injection behavior and document the boundary.",
            articleContent: [
              "Injection testing starts with harmless inputs that reveal parsing behavior. A useful test changes one variable at a time and records both the request and the response.",
              "Do not jump from a signal to destructive proof. In a training environment, the goal is to understand the vulnerable path and produce evidence that a defender or developer can reproduce.",
            ],
          },
          {
            id: "waa-access-control",
            title: "Access Control Checks",
            type: "TEXT",
            durationMinutes: 17,
            order: 2,
            summary: "Test whether resource ownership and role checks hold across common paths.",
            articleContent: [
              "Access control failures often hide in ordinary workflows. Compare what two users with different ownership or roles can read, modify, and delete.",
              "Document the expected rule before showing the bypass. This makes the finding easier to fix and prevents the report from becoming a collection of unrelated screenshots.",
            ],
          },
          {
            id: "waa-reporting",
            title: "Writing the Finding",
            type: "TEXT",
            durationMinutes: 13,
            order: 3,
            summary: "Turn lab evidence into a concise, reproducible report.",
            articleContent: [
              "A strong finding states impact, affected surface, reproduction steps, evidence, and a practical remediation path. Keep speculation out of the main claim.",
              "When the same root cause affects multiple endpoints, group them under one finding and include enough examples to prove the pattern.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "incident-response-operations",
    title: "Incident Response Operations",
    category: "Incident Response",
    shortDescription:
      "Learn the response cadence for triage, containment, recovery, and post-incident review.",
    fullDescription:
      "This course walks through the operator rhythm of incident response. You will move from first signal to action plan, then practice containment and communication choices that keep a response calm and measurable.",
    difficulty: "intermediate",
    tone: "pink",
    hasLabs: false,
    sections: [
      {
        id: "iro-triage",
        title: "Triage",
        description: "Separate signal from noise under time pressure.",
        order: 1,
        lessons: [
          {
            id: "iro-first-hour",
            title: "The First Hour",
            type: "TEXT",
            durationMinutes: 11,
            order: 1,
            summary: "Stabilize the response with scope, severity, owners, and immediate next moves.",
            articleContent: [
              "The first hour is about reducing uncertainty. Capture what triggered the response, what assets might be affected, who owns the decision path, and what action can safely reduce risk.",
              "Avoid overfitting to the first alert. Treat the early narrative as a hypothesis that can change as evidence arrives.",
            ],
          },
          {
            id: "iro-evidence",
            title: "Evidence Handling",
            type: "VIDEO",
            durationMinutes: 8,
            order: 2,
            summary: "Preserve evidence without slowing response.",
            articleContent: [
              "The protected media slot will demonstrate evidence collection order, chain of custody notes, and common mistakes that make later review harder.",
            ],
          },
        ],
      },
      {
        id: "iro-containment",
        title: "Containment",
        description: "Reduce blast radius while maintaining visibility.",
        order: 2,
        lessons: [
          {
            id: "iro-isolation",
            title: "Host Isolation Decisions",
            type: "HYBRID",
            durationMinutes: 18,
            order: 1,
            summary: "Choose isolation steps based on confidence, business impact, and evidence needs.",
            articleContent: [
              "Isolation is a tradeoff. Disconnect too early and you may lose visibility; wait too long and the incident may spread. Use severity, confidence, and business dependency to decide.",
              "When possible, preserve remote collection paths while blocking risky outbound movement. Record the time, owner, reason, and expected rollback condition.",
            ],
          },
          {
            id: "iro-communications",
            title: "Status Communications",
            type: "TEXT",
            durationMinutes: 12,
            order: 2,
            summary: "Keep internal updates factual, brief, and useful for decision makers.",
            articleContent: [
              "Good response updates are factual and time-bound. State what is known, what changed since the last update, what is being done now, and where help is needed.",
              "Avoid dramatic language. Clear communication keeps stakeholders aligned and gives operators room to work.",
            ],
          },
        ],
      },
    ],
  },
  {
    id: "advanced-threat-hunting",
    title: "Advanced Threat Hunting",
    category: "Threat Hunting",
    shortDescription:
      "Use hypotheses, telemetry, and adversary tradecraft to hunt across complex environments.",
    fullDescription:
      "A deeper course for operators who already know the defensive basics. The lessons focus on building hunt hypotheses, choosing telemetry, and iterating when early evidence does not confirm the expected path.",
    difficulty: "advanced",
    tone: "neutral",
    hasLabs: true,
    sections: [
      {
        id: "ath-hypothesis",
        title: "Hunt Design",
        description: "Create focused hunts that can be proven or disproven.",
        order: 1,
        lessons: [
          {
            id: "ath-hypothesis-writing",
            title: "Hypothesis Writing",
            type: "TEXT",
            durationMinutes: 16,
            order: 1,
            summary: "Convert adversary behavior into a measurable question for the environment.",
            articleContent: [
              "A hunt hypothesis links behavior, environment, and evidence. It should be narrow enough to test and broad enough to catch a meaningful class of activity.",
              "Strong hypotheses avoid vendor-specific assumptions until the telemetry plan is clear. Start with the behavior, then translate into available data.",
            ],
          },
          {
            id: "ath-telemetry-fit",
            title: "Telemetry Fit",
            type: "TEXT",
            durationMinutes: 19,
            order: 2,
            summary: "Pick data sources that can answer the hunt question with useful confidence.",
            articleContent: [
              "Telemetry fit is about whether the data can prove or disprove the hypothesis. Missing fields, noisy collection, or short retention can all make a hunt inconclusive.",
              "Record blind spots as outcomes. A hunt that reveals a coverage gap still improves the defensive program when that gap gets prioritized.",
            ],
          },
        ],
      },
      {
        id: "ath-execution",
        title: "Execution",
        description: "Run the hunt and adapt without losing the thread.",
        order: 2,
        lessons: [
          {
            id: "ath-query-review",
            title: "Query Review",
            type: "VIDEO",
            durationMinutes: 12,
            order: 1,
            summary: "Review hunt queries and result pivots through protected training media.",
            articleContent: [
              "The final video service can attach query walkthroughs here. The lesson model already knows this is video-first content with protected media.",
            ],
          },
          {
            id: "ath-findings",
            title: "From Hunt to Finding",
            type: "HYBRID",
            durationMinutes: 20,
            order: 2,
            summary: "Decide whether the result is benign, suspicious, or ready for response.",
            articleContent: [
              "Not every hunt hit is an incident. Compare the result against baseline behavior, asset context, timing, and known administrative activity.",
              "When evidence remains ambiguous, document the next query or data source needed. Good hunting is iterative, not theatrical.",
            ],
          },
          {
            id: "ath-retrospective",
            title: "Hunt Retrospective",
            type: "TEXT",
            durationMinutes: 10,
            order: 3,
            summary: "Capture what improved detection coverage and what still needs instrumentation.",
            articleContent: [
              "A retrospective turns a hunt into program improvement. Capture the hypothesis, data sources, queries, result, coverage gaps, and recommended next hunt.",
              "The most useful output may be a new detection, a tuned alert, a documented blind spot, or a confirmed baseline.",
            ],
          },
        ],
      },
    ],
  },
];
